/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
//see nested vectored interrupt controller

#include <stdio.h>
#include <stdint.h>
#define USART3_IPQNO 39
//because we want to access IRQ #39
//so we should consider the ISPR 1 and ISER 1 (39/32 = 1)
int main(void)
{
	//1. Manually pend the pending bit for the USART IRQ number in NVIC
	//But actually, pending reg will auto set when issue an interrupt
	uint32_t *pISPR1 = (uint32_t*)0XE000E204;
	//find the addr of ISPR 1
	*pISPR1 |= (1 << (USART3_IPQNO % 32));
	//shift by (39%32)

	//2. Enable the USART3 IRQ number in NVIC
	uint32_t *pISER1 = (uint32_t*)0XE000E104;
	//find the addr  of ISER 1
	*pISER1 |= (1 << (USART3_IPQNO % 32));

	//check windows->SFR->NVIC see bit change
	//when the interrupt not working, you should always check these settings(bits)

	//after enable, the interrupt will be handled
	//and the pending state will automatically changed
	for(;;);
}
//go to Startup find USQRT3
void USART3_IRQHandler(void)
{
	printf("in USART3 ISR\n");
}
