/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include<stdio.h>
#define ALIAS_BASE 		0x220000000U
#define BITBAND_BASE 	0x200000000U
int main(void)
{
	//change the 7th bit position of the memory location 0x2000_0200
	//Alias addr = alias_base + (32* (bit_band_memory_addr - bit_band_base)) + bit * 4
	//e.g.0x2200_0000+(32+(0x2000_0200-02000_0000))+7*4

	uint8_t *ptr = (uint8_t*)0x20000200;

	*ptr = 0xff;//reset value
	//normal:read-modify-write
	//clearing 7th bit position
	*ptr &= ~(1 << 7);

	*ptr = 0xff;//reset value
	//bit_band method
	uint8_t *alias_addr = ALIAS_BASE + (32 * (0x20000200 - BITBAND_BASE) + 7 * 4 );
	//clearing 7th bit of addr 0x2000_0200
	*alias_addr = 0;

	//see memory browser 0x20000200 and Disassembly
	//bit banding is faster (3<6)
	for(;;);
}
