/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

#include <stdint.h>
#include <stdio.h>

int func_divide(int x, int y)
{
	return x/y;
}


int main(void)
{
	//1. enable all configurable exceptions like usage fault, mem manage fault and bus fault
	// in m4 document -> system control block -> system handler control and state reg, copy addr
	uint32_t *pSHCSR = (uint32_t*) 0xE000ED24;
	*pSHCSR |= (1 << 16); //mem manage fault
	*pSHCSR |= (1 << 17); //bus fault
	*pSHCSR |= (1 << 18); //usage fault
	//if disable usage fault, it will be hard fault

	//2. enable divided by zero trap
	//check system control block
	uint32_t *pCCR = (uint32_t*)0xE000ED14;
	*pCCR |= (1 << 4);//shift by 4

	//3 devide by 0
	func_divide(10, 0);

	//4. analyze the fault
	//see disassembly
	for(;;);
}
//2. implement the fault handlers
//startup -> every fault name
void HardFault_Handler(void)
{
	printf("Exception: HardFault\n");
	while(1);
}
void MemManage_Handler(void)
{
	printf("Exception: MemManage\n");
	while(1);
}
void BusFault_Handler(void)
{
	printf("Exception: BusFault\n");
	while(1);
}
//because we are writing c function, the stack ptr will be manipulated
__attribute__ ((naked)) void UsageFault_Handler(void)
{	//do not mix c coding in assembly function
	//here we extracted the value of MSP which happens to be the
	//base address of the stack frame (thread mode) which got saved during
	//the exception entry from thread mode to handler mode
	__asm ("MRS r0, MSP");//top of the stack when the exception trigger
	__asm ("B UsageFault_Handler_c");
}
void UsageFault_Handler_c(uint32_t *pBaseStackFrame)//it will call r0
{	//fault here
	//see fault analyzer (故障分析器)
	//see SVM->SVM data console to see printf
	//you can see fault status and addr reg to see How and where fault happened

	uint32_t *pUFSR = (uint32_t*)0xE000ED2A;
	printf("Exception: UsageFault\n");
	printf("UFSR = %lx\n", (*pUFSR) & 0xFFFF);
	printf("MSP = %p\n", pBaseStackFrame);//caution: not to execute exception handler, or it maybe be manipulated
	printf("R0 = %lx\n", pBaseStackFrame[0]);
	printf("R1 = %lx\n", pBaseStackFrame[1]);
	printf("R2 = %lx\n", pBaseStackFrame[2]);//10
	printf("R3 = %lx\n", pBaseStackFrame[3]);//0
	printf("R12 = %lx\n", pBaseStackFrame[4]);
	//Link Register: place of the next instruction from the point exception trigger
	printf("LR = %lx\n", pBaseStackFrame[5]);
	//Program Counter: processor is executing instruction at this location
	//(instruction which is undefined now)
	// just copy addr and check .list file
	printf("PC = %lx\n", pBaseStackFrame[6]);
	printf("XPSR = %lx\n", pBaseStackFrame[7]);
	while(1);
}

